### ISSUE TITLE
How to generate the dataset for dataframe?

### ISSUE THREAD

**Issue by KaminariOS** [uclasystem/DRust#5]
I have got the code compiled and running.
I tried to run the dataframe benchmark.
I went to https://github.com/h2oai/db-benchmark and use commands in the README to generate the dataset.

Then I got an error:

```
start sync server from the spawned thread!
[rust] start
start drust rdma server from the spawned thread!
drust_start_server, trying to bind to 10.0.2.1:9400.
passive_ip_idx: 1
address resolved.
flag_addr: 0x400200000000
flag: 1
atomic_cap: 1
route resolved.
connect request sent.
on_connection
on_connection: Sending MR to the passive side
send completed successfully.
send completed successfully.
Connected!
All servers are ready
start drust distributed alloc server from the spawned thread!
drust dataframe started
start connecting distributed alloc from the spawned thread!
connected to server 0
connected to server 1
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', drust/src/app/dataframe/series/input.rs:17:83
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/f5559e338256f17ada6d82b429acc2dbd8facc9c/library/core/src/result.rs:1651:5
   3: drust::app::dataframe::series::input::read_series::{{closure}}
   4: <drust::drust_std::thread::dlink::DRustServer as drust::drust_std::thread::dlink::DRustWorld>::remote_spawn::{{closure}}
   5: <futures_util::abortable::Abortable<Fut> as core::future::future::Future>::poll
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   7: <tarpc::server::tokio::TokioChannelExecutor<tarpc::server::Requests<C>,S> as core::future::future::Future>::poll::{{closure}}
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
```
> head DRust_home/dataset/dataframe/my_G1_1e8_1e2_0_0.csv
id1,id2,id3,id4,id5,id6,v1,v2,v3
id046,id007,id0000043878,51,10,59276,1,2,9.33179
id041,id026,id0000068300,12,58,78315,4,2,24.555835
id036,id078,id0000012244,25,9,27300,4,15,15.146486
id067,id100,id0000006157,54,38,65416,2,8,68.837472
id047,id025,id0000029319,72,92,19046,4,9,96.766937
id003,id045,id0000068931,87,74,60479,3,6,46.007797
id052,id046,id0000011793,6,32,90599,4,13,14.736708
id024,id050,id0000033725,89,85,8657,3,7,0.185677
id051,id099,id0000018331,12,26,19634,5,6,71.424675
```

**Comment by HarukiMoriarty** [comment]
Hi, I meet with the same issue, do you know how to solve it?
